PISTON_DELIVERY = {
    "EXTENDING_POSITION": 150,
    "RETRACT_POSITION": 300,
    "RESET_POSITION": 0,
    "PISTON_PAUSE": 0.5,
    "POWER_LIMIT": 500,
    "SPEED_LIMIT": 1050
}

PISTON_SORTING = {
    "EXTENDING_POSITION": -350,
    "RETRACT_POSITION": 300,
    "RESET_POSITION": 0,
    "PISTON_PAUSE": 0.5,
    "POWER_LIMIT": 100,
    "SPEED_LIMIT": 2000
}
