PISTON_DELIVERY = {
    "EXTENDING_POSITION": 170,
    "RETRACT_POSITION": 300,
    "RESET_POSITION": 0,
    "PISTON_PAUSE": 0.5,
    "POWER_LIMIT": 80,
    "SPEED_LIMIT": 2050
}

PISTON_SORTING = {
    "EXTENDING_POSITION": -300,
    "RETRACT_POSITION": 300,
    "RESET_POSITION": 0,
    "PISTON_PAUSE": 0.5,
    "POWER_LIMIT": 80,
    "SPEED_LIMIT": 2050
}
